name: Build & Deploy Jupyter-Book

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: pip

    - name: Install dependencies
      run: pip install jupyter-book

    - name: Build the book
      run: jupyter-book build pypsa-workshop

    - name: Add .nojekyll
      run: touch pypsa-workshop/_build/html/.nojekyll

    - name: Upload static site artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: pypsa-workshop/_build/html

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
