name: Build & deploy Jupyter-Book

on:
  push:
    branches: [main]

permissions:
  contents: read    # for checkout
  pages: write      # to update GitHub Pages
  id-token: write   # for actions/deploy-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: "pip"

    - name: Install dependencies
      run: |
        pip install jupyter-book
        pip install -r requirements.txt

    - name: Build the book
      run: jupyter-book build pypsa-workshop

    - name: Add .nojekyll
      run: touch pypsa-workshop/_build/html/.nojekyll

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        publish_dir: pypsa-workshop/_build/html
